version: '3.8'

services:
  sub-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: subwebx:latest
    container_name: sub-webx
    ports:
      - "8088:8088"
    volumes:
      - ./data:/data
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
      - PORT=8088
    restart: unless-stopped
    stop_grace_period: 10s
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8088/api/load-config"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true 