name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: my-image-name:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max